# Notes presentation

Good morning, everyone! I'm MFR, a phd student from RU, and I will present to you an exploratory study on the acquisition of the perfective past time reference in Spanish among Spanish-English early bilinguals

# Studying Variation on Perfectivity

Since the early 2000s, there has been an increasing interest in variationist sociolinguistics in studying the use of the Spanish perfective past time paradigms by monolinguals from different Spanish-speaking countries, as perfectivity can be expressed using the preterit (*bailé*) and the present perfect (*he bailado*).

These studies have identified several key linguistic and social factors that influence the use of preterit and the present perfect, and have revealed differences not only in the usage rates, but also in the factors that constrain their uses. For example, the preterit is considered the default form to express perfectivity in most of the Spanish varieties, but the present perfect is favored and more productively used in Peninsular Spanish. 

---
In addition, the present perfect is generally favored in temporally undetermined contexts and with durative and atelic predicates, but Castilian Spanish prefers it in temporally undetermined and *today* contexts and with achievement verbs. 

Crucially, these studies have demonstrated that these forms represent variable structures in Spanish that overlap functionally within the same context. 

The results from these studies on monolinguals have been compared to those of English L2 learners of Spanish studying abroad, and have suggested that the preterit vis-à-vis present perfect distinction can be acquired by nonnative speakers and that the use of these paradigms depends on the input received. However, the constraints of use of the Spanish present perfect, in particular, in Spanish-English early bilinguals are less clear because there is a lack of research on this phenomenon.

---
# Research Questions
So, with this study, I intended to fill this gap and answer these RQs:

1. What is the frequency of choice of the Spanish preterit and present perfect forms by Spanish-English bilinguals raised in the United States?
2. How does family origin condition the selection of the perfective past time
paradigms in Spanish?
3. Is there a relationship between participant verb form choice, family origin, temporal reference, and lexical aspect?

---
# Methods

### Participants
28 Spanish-English early bilinguals between the ages of 18 and 60 participated in this study. Most of them reported growing up in a Spanish-speaking household, starting learning Spanish when they were infants and English by the start of elementary school.

Participants were divided into four different groups, based on the origin of their families: 
(1) one parent was from Spain and the other from the U.S. (n=3; coded as ‘1Spaniard’); 
(2) both parents were from Spain (n=5; coded as ‘2Spaniards’);
(3) one parent was from Spain and the other from a Caribbean Spanish-speaking
country (n=4; coded as ‘Bidialectal’); and 
(4) one or both parents were from Spanish-speaking countries other than Spain (n=16; coded as ‘Other’).

---
### Materials
Participants completed three tasks on Qualtrics: a demographic and language background questionnaire, a Spanish proficiency test, and a contextualized preference task.

In the contextualized preference task participants were presented with contextualized stories followed by two sentences that differed only in the verb form. Rather than being required to make a forced choice, participants were asked to select the form they preferred or to indicate an equal preference for both structures. 

The linguistic variables that I manipulated were temporal reference and lexical aspect, and the items were controlled for the clause type, person, verb type, and negation. There were a total of 37 items, 18 of which were the experimental stimuli.

---
### Statistical Analysis
I ended up having a dataset of 504 tokens. I analyzed these data using a Bayesian multinomial logistic regression model in R.

Before moving on to the results, I would to mention a couple of things about BDA. Bayesian analysis focuses on understanding the whole range of possibilities within our data and how uncertain we are about them, instead of trying to estimate the only line of best fit. And, to do that, we report the results from the posterior distribution of the model, which represent all the possible outcomes and their corresponding probabilities. So I will not report any *p* values but, rather, I will talk about the probability of the preterit and the present perfect of being selected.

---
# Results

### Frequency of selection
Okay, so, what did I find?

As we can see in this plot...

...The option that was more likely to be chosen was the preterit, with an estimate of .75. The probability of choosing either the present perfect or both paradigms was much lower. These results are not surprising, considering that most of the participants spoke a variety other than Peninsular Spanish, and, thus, they were more likely to favor preterit.

---
### Family origin
I found differences based on family origin.

In all groups the probability of choosing the PRET was higher, followed by "both", except for 2Spaniards, who favored the PPERF over "both". 

In general, the PRET was favored by Other compared to 2Spaniards, but I didn't find differences between 1Spaniard-2Spaniards and Bidialectal-2Spaniards. 

The PPERF was strongly favored by 2Spaniards compared to the other groups.

---
Here we have a plot that shows the results. As you can see, it is not as beautiful, I guess, that the first one I showed you, and that is because the data come from the credible intervals of the posterior distribution of my model, and these intervals are notably wide because the model has a lot of uncertainty, meaning that it needs more data. 

However, despite the fact that the model has a lot of uncertainty, the comparisons still found differences between groups. 

---
### Temporal reference
I also found differences based on temporal reference. 

Overall, the PRET was favored in prehodiernal contexts, followed by hodiernal and temporally vague predicates

For the PPERFT and "both" we see the opposite pattern.

---
Here we can see a plot illustrating the results. 

I really like this plot here, because I think that is giving us a lot of information. As we can see, the credible intervals for the hodiernal and undetermined conditions are wider than those for the prehodiernal, which is not surprising, since the use of the present perfect and the preterit is variable in these context across Spanish varieties. However, I believe that this is telling us that, okay, there is a lot of variability in our data, but that probably something else is going on. 

And, in fact, when I examined temporal reference, along with family origin, I found some interesting results. 

---
### Temporal reference x Family origin

The PRET was strongly favored by Other in undetermined and hodiernal contexts, but that there are no differences between 2Spaniards, 1Spaniard and Bidialectal.

The PPERF was favored by 2Spaniards in hodiernal and undetermined contexts when compared to Other and 1Spaniard, but when compared to Bidialectal, this difference was not that clear.

---
I don't think that I have enough time to talk about the plot what one thing I would like to highlight is that the credible intervals are narrower, so that the variability can be better explain considering temporal reference and family origin altogether. 

---
# Discussion and Conclusion
Okay, so let's recap: I found that the preterit was the preferred choice and the paradigm that was more likely to be chosen, and that the probability of selection of the present perfect varied as a function of family origin and temporal reference, but not lexical aspect. 

The present perfect was favored in hodiernal and undetermined contexts by those participants with familial ties to Spain, but to varying degrees, being the probability of selecting it higher for those participants with two parents from that country. Although I cannot draw any firm conclusions, these differences might be attributed to input quantity, as these groups differed in the variety and/or languages spoken at home, with 2Spaniards being supposedly more exposed to Peninsular Spanish.

Taken together, the results indicate that Spanish-English early bilinguals can acquire the distinction between the past perfective time forms in Spanish. In addition, they show sensitivity to the constraints identified in previous monolingual studies, in the direction of effect established in previous work, suggesting that the variation in the selection of the preterit vs the present perfect is systematic. This systematic variation, then, is akin to monolingual native speakers, especially for those participants with two Spanish-speaking parents.

